# overraching docker-compose file for the backend service

services:
  app:
    # . means build the image from the Dockerfile in the current directory
    build: .
    container_name: habitlink_backend
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=development
      - PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:5000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    image: postgres:13
    container_name: prisma_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: